name: test secrets
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump host variable
        env:
          HOST: ${{ secrets.CDN_HOST }}
        run: echo "$HOST"
